"""
Servidor mínimo de legendas (modo sério local) — Python + yt-dlp.

Uso (2 comandos):
  cd caption-server
  pip install -r requirements.txt
  python app.py

API:
  GET /health
  GET /captions/list?videoId=VIDEO_ID
  GET /captions?videoId=VIDEO_ID&lang=en
"""

from __future__ import annotations

import json
import re
import tempfile
import time
from pathlib import Path

import yt_dlp
from flask import Flask, jsonify, request
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

CACHE_DIR = Path(__file__).parent / "cache"
CACHE_DIR.mkdir(exist_ok=True)

LANG_ALIASES = {
    "en": ["en", "en-US", "en-GB"],
    "pt": ["pt", "pt-BR", "pt-PT"],
    "es": ["es", "es-ES", "es-419", "es-MX"],
}


def _cache_path(video_id: str, lang: str) -> Path:
    safe = re.sub(r"[^a-zA-Z0-9_\-]", "_", f"{video_id}_{lang}")
    return CACHE_DIR / f"{safe}.json"


def _load_cache(video_id: str, lang: str) -> dict | None:
    path = _cache_path(video_id, lang)
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return None
    return None


def _save_cache(video_id: str, lang: str, payload: dict) -> None:
    _cache_path(video_id, lang).write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def _fmt(seconds: float) -> str:
    ms = int(round(max(0.0, seconds) * 1000))
    h, rem = divmod(ms, 3_600_000)
    m, rem = divmod(rem, 60_000)
    s, ms = divmod(rem, 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def _parse_vtt(content: str) -> list[dict]:
    """Converte WEBVTT em lista de cues {start,end,text}."""
    content = content.replace("\r\n", "\n").replace("\r", "\n")
    blocks = re.split(r"\n\s*\n", content.strip())
    cues: list[dict] = []
    time_re = re.compile(
        r"(\d{1,2}:\d{2}:\d{2}[.,]\d{3}|\d{1,2}:\d{2}[.,]\d{3})\s*-->\s*"
        r"(\d{1,2}:\d{2}:\d{2}[.,]\d{3}|\d{1,2}:\d{2}[.,]\d{3})"
    )

    def to_sec(ts: str) -> float:
        ts = ts.replace(",", ".")
        parts = ts.split(":")
        if len(parts) == 3:
            h, m, s = parts
            return int(h) * 3600 + int(m) * 60 + float(s)
        m, s = parts
        return int(m) * 60 + float(s)

    for block in blocks:
        lines = [ln.strip() for ln in block.split("\n") if ln.strip()]
        if not lines:
            continue
        # pula header
        if lines[0].startswith("WEBVTT") or lines[0].startswith("NOTE") or lines[0].startswith("Kind:"):
            continue
        time_idx = next((i for i, ln in enumerate(lines) if "-->" in ln), -1)
        if time_idx < 0:
            continue
        m = time_re.search(lines[time_idx])
        if not m:
            continue
        start, end = to_sec(m.group(1)), to_sec(m.group(2))
        text_lines = lines[time_idx + 1 :]
        text = " ".join(
            re.sub(r"<[^>]+>", "", t).replace("&nbsp;", " ").strip()
            for t in text_lines
        ).strip()
        text = re.sub(r"\s+", " ", text)
        if not text:
            continue
        cues.append({"start": start, "end": end, "text": text})

    # Junta cues consecutivos iguais (VTT auto-caption repete muito)
    merged: list[dict] = []
    for c in cues:
        if merged and merged[-1]["text"] == c["text"]:
            merged[-1]["end"] = c["end"]
        else:
            merged.append(dict(c))
    return merged


def _cues_to_srt(cues: list[dict]) -> str:
    out = []
    for i, c in enumerate(cues, 1):
        out.append(str(i))
        out.append(f"{_fmt(c['start'])} --> {_fmt(c['end'])}")
        out.append(c["text"])
        out.append("")
    return "\n".join(out)


def _extract_info(video_id: str) -> dict:
    url = f"https://www.youtube.com/watch?v={video_id}"
    opts = {
        "skip_download": True,
        "quiet": True,
        "no_warnings": True,
    }
    with yt_dlp.YoutubeDL(opts) as ydl:
        return ydl.extract_info(url, download=False)


def _list_tracks(video_id: str) -> list[dict]:
    info = _extract_info(video_id)
    tracks: list[dict] = []
    seen: set[str] = set()

    for code, items in (info.get("subtitles") or {}).items():
        if code == "live_chat":
            continue
        key = f"{code}|manual"
        if key in seen:
            continue
        seen.add(key)
        name = code
        if items and isinstance(items, list) and items[0].get("name"):
            name = items[0]["name"]
        tracks.append(
            {
                "languageCode": code,
                "languageName": name or code,
                "isAutoGenerated": False,
            }
        )

    for code, items in (info.get("automatic_captions") or {}).items():
        # auto tem muitos "xx-en"; preferimos códigos simples
        if "-" in code and not code.startswith("en"):
            # ainda inclui en-US etc
            pass
        key = f"{code}|auto"
        if key in seen:
            continue
        # evita flood de 100+ auto langs na UI: só principais + en/pt/es
        main = code.split("-")[0].lower()
        if main not in {"en", "pt", "es", "fr", "de", "it", "ja", "ko", "zh", "ru"} and code not in {"en", "pt", "es"}:
            continue
        seen.add(key)
        tracks.append(
            {
                "languageCode": code,
                "languageName": f"{code} (auto)",
                "isAutoGenerated": True,
            }
        )

    tracks.sort(key=lambda t: (t["isAutoGenerated"], t["languageName"].lower()))
    return tracks


def _download_vtt(video_id: str, lang: str) -> tuple[str, str, bool]:
    """
    Baixa VTT com yt-dlp. Retorna (conteúdo, lang_usado, is_auto).
    """
    candidates = LANG_ALIASES.get(lang.lower(), [lang])
    if lang not in candidates:
        candidates = [lang] + candidates

    with tempfile.TemporaryDirectory() as tmp:
        outtmpl = str(Path(tmp) / "%(id)s.%(ext)s")

        # 1) legenda manual
        opts = {
            "skip_download": True,
            "writesubtitles": True,
            "writeautomaticsub": False,
            "subtitleslangs": candidates,
            "subtitlesformat": "vtt",
            "outtmpl": outtmpl,
            "quiet": True,
            "no_warnings": True,
        }
        with yt_dlp.YoutubeDL(opts) as ydl:
            ydl.download([f"https://www.youtube.com/watch?v={video_id}"])

        files = list(Path(tmp).glob("*.vtt"))
        if files:
            path = files[0]
            # tqJQkr-RNEk.en.vtt
            used = path.name.split(".")[-2] if path.name.count(".") >= 2 else lang
            return path.read_text(encoding="utf-8", errors="replace"), used, False

        # 2) auto
        opts["writesubtitles"] = False
        opts["writeautomaticsub"] = True
        with yt_dlp.YoutubeDL(opts) as ydl:
            ydl.download([f"https://www.youtube.com/watch?v={video_id}"])

        files = list(Path(tmp).glob("*.vtt"))
        if not files:
            raise RuntimeError(
                f"Nenhuma legenda VTT para videoId={video_id} lang={lang}"
            )
        path = files[0]
        used = path.name.split(".")[-2] if path.name.count(".") >= 2 else lang
        return path.read_text(encoding="utf-8", errors="replace"), used, True


@app.get("/health")
def health():
    return jsonify(
        {
            "ok": True,
            "service": "linguaplay-captions",
            "engine": "yt-dlp",
            "cache": str(CACHE_DIR),
        }
    )


@app.get("/search")
def search():
    """
    Busca vídeos no YouTube via yt-dlp (sem API key do Google).
    q=termo  lang=en|es|pt  limit=12
    """
    q = (request.args.get("q") or "").strip()
    lang = (request.args.get("lang") or "en").strip().lower()
    try:
        limit = max(1, min(20, int(request.args.get("limit") or "12")))
    except ValueError:
        limit = 12

    if not q:
        return jsonify({"error": "q (busca) obrigatório", "results": []}), 400

    # Viés de idioma na query (yt-dlp não tem filtro oficial de idioma)
    bias = {
        "en": "english",
        "es": "español spanish",
        "pt": "português portuguese",
    }.get(lang, "")
    full_q = f"{q} {bias}".strip() if bias else q

    try:
        opts = {
            "quiet": True,
            "no_warnings": True,
            "extract_flat": True,
            "skip_download": True,
        }
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(f"ytsearch{limit}:{full_q}", download=False)

        entries = info.get("entries") or []
        results = []
        for e in entries:
            if not e:
                continue
            vid = e.get("id") or e.get("url") or ""
            if not vid or len(str(vid)) < 6:
                continue
            # extract_flat às vezes devolve URL completa
            if "watch?v=" in str(vid):
                m = re.search(r"v=([\w-]{11})", str(vid))
                vid = m.group(1) if m else vid
            thumb = None
            thumbs = e.get("thumbnails") or []
            if thumbs:
                thumb = thumbs[-1].get("url")
            thumb = thumb or e.get("thumbnail")
            if not thumb and len(str(vid)) == 11:
                thumb = f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg"
            duration = e.get("duration")
            results.append(
                {
                    "id": str(vid)[:11] if len(str(vid)) >= 11 else str(vid),
                    "title": e.get("title") or str(vid),
                    "author": e.get("uploader")
                    or e.get("channel")
                    or e.get("uploader_id")
                    or "",
                    "thumbnailUrl": thumb,
                    "durationMs": int(duration * 1000) if duration else None,
                }
            )

        return jsonify(
            {
                "q": q,
                "lang": lang,
                "count": len(results),
                "results": results,
                "engine": "yt-dlp",
            }
        )
    except Exception as e:
        return jsonify({"error": str(e), "results": []}), 502


@app.get("/meta")
def meta():
    """Título/thumb/duração sem youtube_explode (só yt-dlp)."""
    video_id = (request.args.get("videoId") or "").strip()
    if not video_id:
        return jsonify({"error": "videoId obrigatório"}), 400
    try:
        info = _extract_info(video_id)
        thumb = None
        thumbs = info.get("thumbnails") or []
        if thumbs:
            thumb = thumbs[-1].get("url")
        thumb = thumb or info.get("thumbnail")
        duration = info.get("duration")
        return jsonify(
            {
                "id": video_id,
                "title": info.get("title") or video_id,
                "author": info.get("uploader") or info.get("channel") or "",
                "thumbnailUrl": thumb,
                "durationMs": int(duration * 1000) if duration else None,
                "engine": "yt-dlp",
            }
        )
    except Exception as e:
        return jsonify({"error": str(e)}), 502


@app.get("/lookup")
def lookup():
    """Tudo num request: meta + lista de legendas (para o app Flutter)."""
    video_id = (request.args.get("videoId") or "").strip()
    if not video_id:
        return jsonify({"error": "videoId obrigatório"}), 400
    try:
        info = _extract_info(video_id)
        thumb = None
        thumbs = info.get("thumbnails") or []
        if thumbs:
            thumb = thumbs[-1].get("url")
        thumb = thumb or info.get("thumbnail")
        duration = info.get("duration")

        # monta tracks a partir do mesmo info (sem 2ª chamada)
        tracks: list[dict] = []
        seen: set[str] = set()
        for code, items in (info.get("subtitles") or {}).items():
            if code == "live_chat":
                continue
            key = f"{code}|manual"
            if key in seen:
                continue
            seen.add(key)
            name = code
            if items and isinstance(items, list) and items[0].get("name"):
                name = items[0]["name"]
            tracks.append(
                {
                    "languageCode": code,
                    "languageName": name or code,
                    "isAutoGenerated": False,
                }
            )
        for code in (info.get("automatic_captions") or {}):
            key = f"{code}|auto"
            if key in seen:
                continue
            main = code.split("-")[0].lower()
            if main not in {
                "en",
                "pt",
                "es",
                "fr",
                "de",
                "it",
                "ja",
                "ko",
                "zh",
                "ru",
            }:
                continue
            seen.add(key)
            tracks.append(
                {
                    "languageCode": code,
                    "languageName": f"{code} (auto)",
                    "isAutoGenerated": True,
                }
            )
        tracks.sort(key=lambda t: (t["isAutoGenerated"], t["languageName"].lower()))

        return jsonify(
            {
                "meta": {
                    "id": video_id,
                    "title": info.get("title") or video_id,
                    "author": info.get("uploader") or info.get("channel") or "",
                    "thumbnailUrl": thumb,
                    "durationMs": int(duration * 1000) if duration else None,
                },
                "tracks": tracks,
                "engine": "yt-dlp",
            }
        )
    except Exception as e:
        return jsonify({"error": str(e)}), 502


@app.get("/captions/list")
def captions_list():
    video_id = (request.args.get("videoId") or "").strip()
    if not video_id:
        return jsonify({"error": "videoId obrigatório"}), 400
    try:
        tracks = _list_tracks(video_id)
        return jsonify({"videoId": video_id, "tracks": tracks, "engine": "yt-dlp"})
    except Exception as e:
        return jsonify({"error": str(e), "tracks": []}), 500


@app.get("/captions")
def captions():
    video_id = (request.args.get("videoId") or "").strip()
    lang = (request.args.get("lang") or "en").strip()
    force = request.args.get("force", "0") == "1"

    if not video_id:
        return jsonify({"error": "videoId obrigatório"}), 400

    if not force:
        cached = _load_cache(video_id, lang)
        if cached:
            cached["cached"] = True
            return jsonify(cached)

    t0 = time.time()
    try:
        vtt, lang_used, is_auto = _download_vtt(video_id, lang)
        cues = _parse_vtt(vtt)
        if not cues:
            raise RuntimeError("VTT vazio após parse")
    except Exception as e:
        return jsonify({"error": f"Falha ao baixar legenda: {e}"}), 502

    srt = _cues_to_srt(cues)
    payload = {
        "videoId": video_id,
        "lang": lang_used,
        "requestedLang": lang,
        "isAutoGenerated": is_auto,
        "cached": False,
        "ms": int((time.time() - t0) * 1000),
        "engine": "yt-dlp",
        "cues": cues,
        "srt": srt,
        "count": len(cues),
    }
    _save_cache(video_id, lang, payload)
    if lang_used != lang:
        _save_cache(video_id, lang_used, payload)
    return jsonify(payload)


if __name__ == "__main__":
    import os

    port = int(os.environ.get("PORT", "8765"))
    print("=" * 50)
    print(" LinguaPlay caption server (yt-dlp)")
    print(f" PORT={port}")
    print(" health:   /health")
    print(" search:   /search?q=...&lang=en")
    print(" captions: /captions?videoId=...&lang=en")
    print("=" * 50)
    app.run(host="0.0.0.0", port=port, debug=False, threaded=True)
